# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'SaitamaBicycle' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 3.4'
  pod 'GoogleMaps'

  # Pods for SaitamaBicycle

  target 'SaitamaBicycleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SaitamaBicycleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
